apiVersion: v1
kind: Service 
metadata: 
  name: service-clusterip-mysql
spec: 
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
  - protocol: TCP        
    port: 3306 
    targetPort: 3306
